import { Link } from 'react-router-dom'
import { photos } from '../data'
import { Button, Kicker } from '../components/Layout'
import MenuCard from '../components/MenuCard'

export default function Home() {
  return <main>
    <section className="hero section-pad">
      <div className="hero-copy"><p className="eyebrow">Pizzeria · Coffee · Vegan · Italian</p><h1>Good food,<br/><em>slow moments.</em></h1><p className="hero-intro">A soulful little dining space in Pushkar for wood-fired pizzas, golden coffee and conversations that linger.</p><div className="hero-actions"><Button to="/menu">Explore the menu</Button><Link className="text-link" to="/about">Get to know us <span>↓</span></Link></div></div>
      <div className="hero-visual"><img src={photos.hero} alt="Fresh pizza on a table"/><div className="hero-stamp"><span>Made with</span><strong>♡</strong><span>in Pushkar</span></div></div>
    </section>
    <section className="ticker"><span>CASA LUNA</span><i>✦</i><span>ITALIAN SOUL</span><i>✦</i><span>PUSHKAR SUNSETS</span><i>✦</i><span>GOOD FOOD</span></section>
    <section className="story section-pad"><Kicker>01 / The feeling</Kicker><div className="story-grid"><h2>A table for every<br/><em>kind of day.</em></h2><div><p className="large-copy">Casa Luna brings the warmth of a bohemian café to Sunset Street — with the generous flavours of Italy and a little something for every appetite.</p><p className="body-copy">Come for a relaxed coffee, stay for the pizza, and leave with the feeling that you found a new favourite corner of Pushkar.</p><Link className="text-link" to="/about">Our little corner of Pushkar <span>↗</span></Link></div></div><div className="story-image"><img src={photos.table} alt="Casa Luna dining space"/></div></section>
    <section className="menu section-pad"><Kicker>02 / From the kitchen</Kicker><div className="menu-head"><h2>Made to be<br/><em>shared.</em></h2><p>Italian comfort, local colour, and plenty of room to follow your mood.</p></div><div className="menu-cards"><MenuCard image={photos.pizza} title="The salad" text="Fresh greens, colourful vegetables, and a crisp, refreshing bite."/><MenuCard image={photos.pasta} title="The chocolate" text="Rich, chocolatey, and made for a deliciously sweet pause."/><MenuCard image={photos.coffee} title="The sweet" text="A comforting baked treat to enjoy with your coffee."/></div><div className="menu-footer"><span>Vegetarian · Vegan-friendly · Made fresh</span><Button to="/menu" light>View full menu</Button></div></section>
    <section className="return-section section-pad"><Kicker>03 / Why people come back</Kicker><div className="return-grid"><div><h2>Slow food,<br/><em>easy mornings.</em></h2><p className="return-copy">Whether it is a quick espresso before the market, a long lunch with friends, or a pizza night under the lights, Casa Luna is designed to feel like a place you can settle into.</p><div className="day-parts"><div><strong>11am</strong><span>Coffee & croissant</span></div><div><strong>1pm</strong><span>Lunch with friends</span></div><div><strong>8pm</strong><span>Wood-fired evenings</span></div></div></div><div className="return-images"><img src={photos.table} alt="Cozy interior seating"/><img src={photos.coffee} alt="Coffee at Casa Luna"/></div></div></section>
    <section className="weekly-section section-pad"><Kicker>04 / This week at Casa Luna</Kicker><div className="weekly-grid"><article><p className="eyebrow">Daily ritual</p><h3>Pizza nights</h3><p>Wood-fired favourites, warm lighting, and a table ready for long conversations.</p></article><article><p className="eyebrow">Slow mornings</p><h3>Coffee & calm</h3><p>Fresh brews, mellow playlists, and a little space to pause before the day begins.</p></article><article><p className="eyebrow">Sweet finish</p><h3>Something special</h3><p>Desserts and mocktails that turn a casual stop into a full evening to remember.</p></article></div><div className="weekly-callout"><div><p className="eyebrow">Plan your visit</p><h3>Ready for a slow, beautiful meal?</h3></div><Button to="/visit">Find a table</Button></div></section>
  </main>
}
